language: python
python:
- 3.6
- 3.5
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tbuli
  password:
    secure: nUC6xBEnEvffpiHinT5Pfyt6BJhQHXTYJYqbCwdeodrvkg+EY0v+D44gcFLYSAPjoWwQENvQaC8ys/HMf/SH1TJ0yx21C9HD4xdMIlgSJrUwAfOLvZMoHjmKx7mWQw840rcucTwGzQ91Ts086IYx6ba6X2P3ObSxPliJp4NUzwZG3AO5RmOk/WOf2YnA6j6C7rX5g+h6RQhfGa3oycKwNRsx5TfLokDV1+PXtqZ+oee+3EIe3Htfmx0P1q06ARPSUXkv6njUVatpO3Ykhe0Cqf3suz6eA1aztwix5vtf6wrnivpczj5K+njC/s40izSpvetiqWASo5Ym42lucyg/UB42rUa/lSW58BwVXjsqmIqO9tsLfGO81/3E9Ou3K6s0p8rSlTP86mgbJR5y40/+rYWAeiK8qU+obmCrdmrh/aRY5PWYyHUM0eGkiagfbuZ4dkMEzHbE0XBbxbE6mxDROWebnUCgdbgfPB9gEJPlT/OVBpychJdCyFlrXCdULY8XbR4/5L9Rj00cRdt2QtDke6Ceoo7j28FCKPiCwSKaT2I0nLVXGeAknVGhyEQTLtLC08MNn29o7PzAGfOZpd0aGJ2fdC37Bcl3YPvMmtMbv6vMviNWcNtv7GCEP2b8AFfOzOX8M1li0atNbIX4j5EzLQ4pvwOOGiVbIBlvNmaIy9Q=
  on:
    tags: true
    repo: tbuli/tikhonov
    python: 3.6
